### ISSUE TITLE
Should I be able to execute a SELECT inside a transaction?

### ISSUE THREAD

**Issue by mark-rushakoff** [cznic/ql#108]
I have some code that's trying to run a SELECT statement inside a transaction. It isn't working, and I'm not if *should* work.

Here's a trivial piece of code for what's going wrong:

```go
package main

import (
	"github.com/cznic/ql"
)

func main() {
	db, err := ql.OpenMem()
	if err != nil {
		panic(err)
	}

	// Create a table and insert some values without completing the transaction
	setup := `BEGIN TRANSACTION;
CREATE TABLE people (name string NOT NULL);
INSERT INTO people VALUES ("alice"), ("bob");
`
	ctx := ql.NewRWCtx()
	_, _, err = db.Run(ctx, setup)
	if err != nil {
		panic(err)
	}

	println("about to execute nested SELECT")
	rs, _, err := db.Run(ctx, "SELECT count() FROM people;") // if ctx is nil, this line hangs
	if err != nil {
		panic(err)
	}

	println("About to get the first row")
	row, err := rs[0].FirstRow() // blocks forever
	if err != nil {
		panic(err)
	}
	println(row)

	_, _, err = db.Run(ctx, "COMMIT;")
	if err != nil {
		panic(err)
	}
	println("DONE")
}
```

It hangs on the call to `rs[0].FirstRow()`, and the stack trace from ctrl-\ is shown:

```
$ go run main.go
about to execute nested SELECT
About to get the first row
^\SIGQUIT: quit
PC=0x405d97b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0xe03, 0x402283d, 0x48229a0, 0x0, 0x4a05ea0, 0x4814180, 0x40506f9, 0xffffffffffffffff, 0x48229a0, 0x7fff5fbff63c, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x48229a0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/os1_darwin.go:385 +0xe5
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/os1_darwin.go:401 +0x29
runtime.systemstack(0x7fff5fbff640)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:278 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/os1_darwin.go:402 +0x36
runtime.notesleep(0x4814830)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/lock_sema.go:169 +0x100
runtime.stopm()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:1128 +0x112
runtime.findrunnable(0xc82001c000, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:1530 +0x69e
runtime.schedule()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc820000180)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7fff5fbff7c0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc820058880)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xc820058874)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/rwmutex.go:36 +0x58
github.com/cznic/ql.(*DB).do(0xc820058850, 0xc820107dc0, 0x4bb5120, 0xc820105d00, 0x0, 0xc820107e40, 0x0, 0x0)
	/Users/mr/go/src/github.com/cznic/ql/ql.go:1376 +0x28d
github.com/cznic/ql.recordset.Do(0xc820107dc0, 0x4bb5120, 0xc820105d00, 0x0, 0x0, 0xc820107e40, 0x0, 0x0)
	/Users/mr/go/src/github.com/cznic/ql/ql.go:75 +0x115
github.com/cznic/ql.recordset.Rows(0xc820107dc0, 0x4bb5120, 0xc820105d00, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mr/go/src/github.com/cznic/ql/ql.go:100 +0x15a
github.com/cznic/ql.recordset.FirstRow(0xc820107dc0, 0x4bb5120, 0xc820105d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/mr/go/src/github.com/cznic/ql/ql.go:85 +0x85
github.com/cznic/ql.(*recordset).FirstRow(0xc820107e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:62 +0xb7
main.main()
	/Users/mr/go/src/qltest/main.go:30 +0x26e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

rax    0xe
rbx    0xe03
rcx    0x7fff5fbff5c8
rdx    0x7fff5fbff640
rdi    0xe03
rsi    0x4814180
rbp    0x4814720
rsp    0x7fff5fbff5c8
r8     0x4814720
r9     0x0
r10    0x44c1220
r11    0x286
r12    0x10
r13    0x4663956
r14    0xe
r15    0x8
rip    0x405d97b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

Should I be able to execute a SELECT statement inside an unfinished transaction?

**Comment by cznic** [comment]
> It isn't working, and I'm not if should work.

It should work.

This is essentially #56 again. The fix extended the `recordset` with a `tx` (transaction context) field which is correctly set only when using the `database/sql` API. This issue is the same thing happening on the direct API, because the tx field is, incorrectly, left `nil`.

**Comment by cznic** [comment]
@mark-rushakoff 
Thanks for the report. Please test and feel free to reopen if the fix does not work for you.
