### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cryptix** [cznic/ql#110]
Can you make something out of this crash?

It happens 10 out of ~45.000 runs on my test suite using [stress](https://golang.org/x/tools/cmd/stress).

I was able to produce these under go 1.5.1 with freebsd/amd64 and linux/amd64.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x73574a]

goroutine 36 [running]:
github.com/cznic/ql.(*table).row0(0xc8204030e0, 0xc82042be60, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/storage.go:778 +0xba
github.com/cznic/ql.(*tableDefaultPlan).do(0xc82042be80, 0xc82042be60, 0xc820448dc0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:2402 +0xa8
github.com/cznic/ql.(*filterDefaultPlan).do(0xc820448d00, 0xc82042be60, 0xc820448d80, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1460 +0x1a5
github.com/cznic/ql.(*selectFieldsDefaultPlan).do(0xc820448d40, 0xc82042be60, 0xc82042bf60, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1987 +0x1a5
github.com/cznic/ql.(*DB).do(0xc82037dd50, 0xc82042be60, 0x80200a6e0, 0xc820448d40, 0x0, 0xc82043eeb0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1397 +0x178
github.com/cznic/ql.recordset.Do(0xc82042be60, 0x80200a6e0, 0xc820448d40, 0x0, 0x0, 0xc82043eeb0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:75 +0x115
github.com/cznic/ql.(*recordset).Do(0xc82042bf00, 0xc82043ee00, 0xc82043eeb0, 0x0, 0x0)
	<autogenerated>:60 +0xb5
github.com/cznic/ql.newdriverRows.func1(0xc82042bf20)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:387 +0xae
created by github.com/cznic/ql.newdriverRows
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:402 +0xeb

goroutine 1 [chan receive]:
testing.RunTests(0xc1b5e0, 0xfe6d40, 0x18, 0x18, 0xb17901)
	/home/cryptix/gotip/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200b1ee8, 0xc8201130e0)
	/home/cryptix/gotip/src/testing/testing.go:494 +0x70
main.main()
	projX/sysdb/qlstore/_test/_testmain.go:100 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/cryptix/gotip/src/runtime/asm_amd64.s:1696 +0x1

goroutine 26 [runnable]:
github.com/cznic/ql.(*mem).Create(0xc82046a000, 0xc8204603c0, 0x6, 0x6, 0x7, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/mem.go:450 +0x47f
github.com/cznic/ql.(*table).addIndex0(0xc8204840f0, 0x0, 0xc820454850, 0xa, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/storage.go:562 +0x354
github.com/cznic/ql.(*table).addIndex(0xc8204840f0, 0x0, 0xc820454850, 0xa, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/storage.go:595 +0x78
github.com/cznic/ql.(*createIndexStmt).exec(0xc820460360, 0xc820458580, 0x0, 0x0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/stmt.go:1124 +0x8b6
github.com/cznic/ql.(*DB).run1(0xc82045c380, 0xc820454430, 0x802004ce8, 0xc820460360, 0x103fa48, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1337 +0x13af
github.com/cznic/ql.(*DB).Execute(0xc82045c380, 0xc820454430, 0xc8204584a0, 0x2, 0x2, 0x0, 0x103fa48, 0x0, 0x0, 0x0, ...)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1197 +0x273
github.com/cznic/ql.driverExec(0xc8204581e0, 0xc820454430, 0xc8204584a0, 0x2, 0x2, 0x0, 0x103fa48, 0x0, 0x0, 0x0, ...)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:305 +0xf9
github.com/cznic/ql.(*driverConn).Exec(0xc820462270, 0xc23340, 0x88, 0x103fa48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:301 +0x12e
database/sql.(*Tx).Exec(0xc82046a050, 0xc23340, 0x88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cryptix/gotip/src/database/sql/sql.go:1267 +0x276
projX/sysdb/qlstore.Create.func1(0xc82046a050, 0x0, 0x0)
	/home/cryptix/proj/src/projX/sysdb/qlstore/ql.go:148 +0x119
projX/sysdb/qlstore.transact(0xc820466000, 0xc8200ad878, 0x0, 0x0)
	/home/cryptix/proj/src/projX/sysdb/qlstore/ql.go:164 +0xd4
projX/sysdb/qlstore.Create(0xc820466000, 0x0, 0x0)
	/home/cryptix/proj/src/projX/sysdb/qlstore/ql.go:146 +0x177
projX/sysdb/qlstore.TestBehaviour_ArchiveDB.func1()
	/home/cryptix/proj/src/projX/sysdb/qlstore/archive_test.go:264 +0x14e
github.com/smartystreets/goconvey/convey.parseAction.func1(0x802009cc8, 0xc820272960)
	/home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x18
github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc820272960, 0xb1ac00, 0xf, 0xc820255200)
	/home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x21a
github.com/smartystreets/goconvey/convey.rootConvey.func1()
	/home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x142
github.com/jtolds/gls._m(0x0, 0xc820224940)
	/home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x2b
github.com/jtolds/gls.markS(0x0, 0xc820224940)
	/home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x2b
github.com/jtolds/gls.addStackTag(0x0, 0xc820224940)
	/home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x37
github.com/jtolds/gls.(*ContextManager).SetValues(0xc82010ea40, 0xc8201ddce0, 0xc820224940)
	/home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x4e6
github.com/smartystreets/goconvey/convey.rootConvey(0xc8200adf10, 0x3, 0x3)
	/home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x3e6
github.com/smartystreets/goconvey/convey.Convey(0xc8200adf10, 0x3, 0x3)
	/home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x45
projX/sysdb/qlstore.TestBehaviour_ArchiveDB(0xc820087950)
	/home/cryptix/proprojore/archive_test.go:489 +0x175
testing.tRunner(0xc820087950, 0xfe6e30)
	/home/cryptix/gotip/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/cryptix/gotip/src/testing/testing.go:561 +0x86d

goroutine 50 [runnable]:
database/sql.(*DB).connectionOpener(0xc820466000)
	/home/cryptix/gotip/src/database/sql/sql.go:633
created by database/sql.Open
	/home/cryptix/gotip/src/database/sql/sql.go:481 +0x336


ERROR: exit status 2
```

**Comment by cznic** [comment]
I have no idea how can I reproduce the issue. Please advise.

Anyway, a data race (in ql) is the usual suspect. Can you please try to build your test binary, which is then `stress`ed, using the `-race` option and catch the error under the race detector?

**Comment by cznic** [comment]
@cryptix 
Also, is your vendored ql revision the same (latest) version as my `master`?

**Comment by cryptix** [comment]
re version: I ran this on 9c77931b60c6317f94de402268bbc3e8334b71f4 and than updated to b0c21f49a6f275ab43692fd5d9e9d2e5645293a3 to make sure it wasn't fixed.

re race: Indeed! Seeing the trace this might as well be a byproduct of my testing setup...

I'll reopen when I can reproduce this without goconvey/goroutine local storage involved.

```
==================
WARNING: DATA RACE
Write by goroutine 26:
  github.com/cznic/ql.(*mem).Close()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/mem.go:284 +0xe8
  github.com/cznic/ql.(*DB).Close()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1365 +0x180
  github.com/cznic/ql.(*driverConn).Close()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:237 +0x4f9
  database/sql.(*driverConn).finalClose()
      /home/cryptix/gotip/src/database/sql/sql.go:348 +0x16d
  database/sql.(finalCloser).(database/sql.finalClose)-fm()
      /home/cryptix/gotip/src/database/sql/sql.go:437 +0x4d
  database/sql.(*DB).Close()
      /home/cryptix/gotip/src/database/sql/sql.go:522 +0x48a
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:267 +0x31
  github.com/smartystreets/goconvey/convey.(*context).conveyInner.func3()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:253 +0x91
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:263 +0x23c
  github.com/smartystreets/goconvey/convey.rootConvey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x1f0
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.rootConvey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x546
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x52
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:489 +0x1c5
  testing.tRunner()
      /home/cryptix/gotip/src/testing/testing.go:456 +0xdc

Previous read by goroutine 36:
  github.com/cznic/ql.(*mem).Read()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/mem.go:456 +0x87
  github.com/cznic/ql.(*table).row0()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/storage.go:778 +0x10b
  github.com/cznic/ql.(*tableDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:2402 +0xe3
  github.com/cznic/ql.(*filterDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1460 +0x261
  github.com/cznic/ql.(*selectFieldsDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1987 +0x26b
  github.com/cznic/ql.(*DB).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1397 +0x1ed
  github.com/cznic/ql.recordset.Do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:75 +0x14a
  github.com/cznic/ql.(*recordset).Do()
      <autogenerated>:60 +0xd9
  github.com/cznic/ql.newdriverRows.func1()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:394 +0x10f

Goroutine 26 (running) created at:
  testing.RunTests()
      /home/cryptix/gotip/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /home/cryptix/gotip/src/testing/testing.go:494 +0xe4
  main.main()
      proxJ/sysdb/qlstore/_test/_testmain.go:100 +0x20f

Goroutine 36 (finished) created at:
  github.com/cznic/ql.newdriverRows()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:402 +0x13f
  github.com/cznic/ql.driverQuery()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:349 +0x26f
  github.com/cznic/ql.(*driverConn).Query()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:336 +0x18d
  database/sql.(*DB).queryConn()
      /home/cryptix/gotip/src/database/sql/sql.go:977 +0x228
  database/sql.(*DB).query()
      /home/cryptix/gotip/src/database/sql/sql.go:964 +0x176
  database/sql.(*DB).Query()
      /home/cryptix/gotip/src/database/sql/sql.go:947 +0xb9
  database/sql.(*DB).QueryRow()
      /home/cryptix/gotip/src/database/sql/sql.go:1028 +0x70
  proxJ/sysdb/qlstore.ArchiveDB.GetJobIDByName()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive.go:366 +0x19e
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.7.1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:307 +0x62
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.(*context).Convey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:163 +0x7d
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.mark2()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:24 +0x38
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:72 +0x90
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.(*context).Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:164 +0x4ce
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:77 +0x74
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.7()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:310 +0x3ec
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.(*context).Convey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:163 +0x7d
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.mark1()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:23 +0x38
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:72 +0x90
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.(*context).Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:164 +0x4ce
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:77 +0x74
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:487 +0xe69
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.rootConvey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x1f0
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.rootConvey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x546
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x52
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:489 +0x1c5
  testing.tRunner()
      /home/cryptix/gotip/src/testing/testing.go:456 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 26:
  github.com/cznic/ql.(*DB).Close()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1366 +0x1c0
  github.com/cznic/ql.(*driverConn).Close()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:237 +0x4f9
  database/sql.(*driverConn).finalClose()
      /home/cryptix/gotip/src/database/sql/sql.go:348 +0x16d
  database/sql.(finalCloser).(database/sql.finalClose)-fm()
      /home/cryptix/gotip/src/database/sql/sql.go:437 +0x4d
  database/sql.(*DB).Close()
      /home/cryptix/gotip/src/database/sql/sql.go:522 +0x48a
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:267 +0x31
  github.com/smartystreets/goconvey/convey.(*context).conveyInner.func3()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:253 +0x91
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:263 +0x23c
  github.com/smartystreets/goconvey/convey.rootConvey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x1f0
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.rootConvey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x546
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x52
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:489 +0x1c5
  testing.tRunner()
      /home/cryptix/gotip/src/testing/testing.go:456 +0xdc

Previous read by goroutine 36:
  github.com/cznic/ql.(*table).row0()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/storage.go:778 +0x85
  github.com/cznic/ql.(*tableDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:2402 +0xe3
  github.com/cznic/ql.(*filterDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1460 +0x261
  github.com/cznic/ql.(*selectFieldsDefaultPlan).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/plan.go:1987 +0x26b
  github.com/cznic/ql.(*DB).do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:1397 +0x1ed
  github.com/cznic/ql.recordset.Do()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/ql.go:75 +0x14a
  github.com/cznic/ql.(*recordset).Do()
      <autogenerated>:60 +0xd9
  github.com/cznic/ql.newdriverRows.func1()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:394 +0x10f

Goroutine 26 (running) created at:
  testing.RunTests()
      /home/cryptix/gotip/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /home/cryptix/gotip/src/testing/testing.go:494 +0xe4
  main.main()
      proxJ/sysdb/qlstore/_test/_testmain.go:100 +0x20f

Goroutine 36 (finished) created at:
  github.com/cznic/ql.newdriverRows()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:402 +0x13f
  github.com/cznic/ql.driverQuery()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:349 +0x26f
  github.com/cznic/ql.(*driverConn).Query()
      /home/cryptix/proj/vendor/src/github.com/cznic/ql/driver.go:336 +0x18d
  database/sql.(*DB).queryConn()
      /home/cryptix/gotip/src/database/sql/sql.go:977 +0x228
  database/sql.(*DB).query()
      /home/cryptix/gotip/src/database/sql/sql.go:964 +0x176
  database/sql.(*DB).Query()
      /home/cryptix/gotip/src/database/sql/sql.go:947 +0xb9
  database/sql.(*DB).QueryRow()
      /home/cryptix/gotip/src/database/sql/sql.go:1028 +0x70
  proxJ/sysdb/qlstore.ArchiveDB.GetJobIDByName()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive.go:366 +0x19e
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.7.1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:307 +0x62
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.(*context).Convey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:163 +0x7d
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.mark2()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:24 +0x38
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:72 +0x90
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.(*context).Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:164 +0x4ce
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:77 +0x74
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1.7()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:310 +0x3ec
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.(*context).Convey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:163 +0x7d
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.mark1()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:23 +0x38
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:72 +0x90
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.(*context).Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:164 +0x4ce
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:77 +0x74
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB.func1()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:487 +0xe69
  github.com/smartystreets/goconvey/convey.parseAction.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x29
  github.com/smartystreets/goconvey/convey.(*context).conveyInner()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x28c
  github.com/smartystreets/goconvey/convey.rootConvey.func1()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x1f0
  github.com/jtolds/gls._m()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:70 +0x39
  github.com/jtolds/gls.markS()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:21 +0x38
  github.com/jtolds/gls.addStackTag()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/stack_tags.go:18 +0x49
  github.com/jtolds/gls.(*ContextManager).SetValues()
      /home/cryptix/proj/vendor/src/github.com/jtolds/gls/context.go:98 +0x609
  github.com/smartystreets/goconvey/convey.rootConvey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x546
  github.com/smartystreets/goconvey/convey.Convey()
      /home/cryptix/proj/vendor/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x52
  proxJ/sysdb/qlstore.TestBehaviour_ArchiveDB()
      /home/cryptix/proj/src/proxJ/sysdb/qlstore/archive_test.go:489 +0x1c5
  testing.tRunner()
      /home/cryptix/gotip/src/testing/testing.go:456 +0xdc
==================
```
