### ISSUE TITLE
can't UPDATE column with nil value

### ISSUE THREAD

**Issue by cryptix** [cznic/ql#84]
Hi,

when I run the following snippet I get `panic: interface conversion: interface is nil, not ql.chunk`

```sql
CREATE TABLE testA (
	comment string,
	data blob,
);
INSERT INTO testA (comment) VALUES ("c1");
UPDATE testA SET data = blob("newVal");
```

```
[cryptix@higgs /tmp/qlupdatebug] ql < testql
panic: interface conversion: interface is nil, not ql.chunk

goroutine 1 [running]:
github.com/cznic/ql.(*file).UpdateRow(0xc208011ab0, 0x6, 0xc20802e780, 0x1, 0x1, 0xc20809a3c0, 0x4, 0x4, 0x0, 0x0)
        /home/cryptix/go/src/github.com/cznic/ql/file.go:991 +0x236
github.com/cznic/ql.(*updateStmt).exec(0xc20809a240, 0xc20801ffe0, 0x0, 0x0, 0x0, 0x0)
        /home/cryptix/go/src/github.com/cznic/ql/stmt.go:164 +0x107f
github.com/cznic/ql.(*DB).run1(0xc20805ad20, 0xc20802ba10, 0xc20808f908, 0x7faa89c36c80, 0xc20809a240, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/cryptix/go/src/github.com/cznic/ql/ql.go:1945 +0x1615
github.com/cznic/ql.(*DB).Execute(0xc20805ad20, 0xc20802ba10, 0xc208052100, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/cryptix/go/src/github.com/cznic/ql/ql.go:1802 +0x282
main.do(0x7faa89c31dc0, 0xc20802bc80)
        /home/cryptix/go/src/github.com/cznic/ql/ql/main.go:186 +0x14aa
main.main()
        /home/cryptix/go/src/github.com/cznic/ql/ql/main.go:79 +0x1f

goroutine 2 [runnable]:
runtime.forcegchelper()
        /home/cryptix/gotip/src/runtime/proc.go:90
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /home/cryptix/gotip/src/runtime/mgc0.go:82
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /home/cryptix/gotip/src/runtime/malloc.go:712
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/cryptix/gotip/src/runtime/asm_amd64.s:2232 +0x1
```

Updating rows where `data != nil` works. This feels like a regression from #68 but I couldn't make it work by resetting the code to an older state.

**Comment by cznic** [comment]
Thanks for the report, I can reproduce the crash.

```
jnml@4670:~/tmp$ cat 84.ql 
CREATE TABLE testA (
    comment string,
    data blob,
);
INSERT INTO testA (comment) VALUES ("c1");
UPDATE testA SET data = blob("newVal");
jnml@4670:~/tmp$ rm -f ql.db
jnml@4670:~/tmp$ ql < 84.ql 
panic: interface conversion: interface is nil, not ql.chunk

goroutine 1 [running]:
github.com/cznic/ql.(*file).UpdateRow(0xc208011260, 0x6, 0xc20802c708, 0x1, 0x1, 0xc20808a340, 0x4, 0x4, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/ql/file.go:991 +0x236
github.com/cznic/ql.(*updateStmt).exec(0xc20808a1c0, 0xc208056260, 0x0, 0x0, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/ql/stmt.go:164 +0x107f
github.com/cznic/ql.(*DB).run1(0xc20805a960, 0xc20800bcb0, 0xc20809b908, 0x7fbe2e244ec8, 0xc20808a1c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jnml/src/github.com/cznic/ql/ql.go:1945 +0x1615
github.com/cznic/ql.(*DB).Execute(0xc20805a960, 0xc20800bcb0, 0xc20805e180, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jnml/src/github.com/cznic/ql/ql.go:1802 +0x282
main.do(0x7fbe2e23ff08, 0xc20800bf20)
	/home/jnml/src/github.com/cznic/ql/ql/main.go:186 +0x14aa
main.main()
	/home/jnml/src/github.com/cznic/ql/ql/main.go:79 +0x1f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/jnml/go/src/runtime/asm_amd64.s:2232 +0x1
jnml@4670:~/tmp$ 
```

**Comment by cryptix** [comment]
Perfect. Thanks!

**Comment by cznic** [comment]
This time it was a bit sooner ;-)
